apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: devops-lab
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: ghcr.io/leonelarellanomontalvo/spring-petclinic:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 15
            failureThreshold: 10
          resources:
            requests:
              memory: "384Mi"
              cpu: "300m"
            limits:
              memory: "768Mi"
              cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: devops-lab
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-hpa
  namespace: devops-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50