apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-monitor
  namespace: monitoring
  labels:
    release: prom
spec:
  namespaceSelector:
    matchNames:
      - devops-lab
  selector:
    matchLabels:
      app: petclinic
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s